### PR TITLE
Fix compilation errors on CentOS

### PR DESCRIPTION
**Pull request by DavidFair**
Fixes various issues preventing the new starter exercises building, see commits for details

### CODE REVIEW

**Review by DanielMurphy22 — APPROVED** [review]
Of course this would fail the build server. Good to have this fixed so it compiles against C++17

**Comment by DavidFair** [comment]
I've updated the build servers to use Python 3 and added a small sample project so we can easily tell if it's the CI or new code causing issues (so a new starter will hopefully report broken CI earlier on)

I've also tweaked the Jenkins jobs not to delete the repos between, since we clone ~500MB each pass and already delete the build dir between runs anyway

@DanielMurphy22 could you give this a re-review when you get a chance

**Review by DanielMurphy22 — APPROVED** [review]
I like the new verb "F-string -inate"

**Comment by DavidFair** [comment]
Build failures are expected as we don't have any projects for the CI to officially build
@martyngigg When you get a chance could you review / merge this? I don't have the merge permission on this repo

**Review by martyngigg — APPROVED** [review]
Thanks for looking at this. This always gets left out in the cold until someone new gets around to it.

**Comment by martyngigg** [comment]
> I've also tweaked the Jenkins jobs not to delete the repos between, since we clone ~500MB each pass and already delete the build dir between runs anyway

Is this repo really that big?

**Comment by DavidFair** [comment]
> > I've also tweaked the Jenkins jobs not to delete the repos between, since we clone ~500MB each pass and already delete the build dir between runs anyway
> 
> Is this repo really that big?

Huh I just cloned it again to check, now only 137MB instead of the 500MB ish - we do have a new router arriving today as I have had real problems with packet storms on our LAN / corruption etc. so I wonder if this was git trying over and over to get valid pack files :confused: 

I originally assumed people had pushed binaries in the past, but ignore me completely on that one

**Comment by DanielMurphy22** [comment]
> > > I've also tweaked the Jenkins jobs not to delete the repos between, since we clone ~500MB each pass and already delete the build dir between runs anyway
> > 
> > 
> > Is this repo really that big?
> 
> Huh I just cloned it again to check, now only 137MB instead of the 500MB ish - we do have a new router arriving today as I have had real problems with packet storms on our LAN / corruption etc. so I wonder if this was git trying over and over to get valid pack files 😕
> 
> I originally assumed people had pushed binaries in the past, but ignore me completely on that one

It was also slow for me cloning to my Mac on site over VPN yesterday afternoon.

**Pull request merged**
